/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clerk from "../clerk.js";
import type * as favorites from "../favorites.js";
import type * as http from "../http.js";
import type * as newsletters from "../newsletters.js";
import type * as portfolios from "../portfolios.js";
import type * as submissions from "../submissions.js";
import type * as templates from "../templates.js";
import type * as uploads from "../uploads.js";
import type * as users from "../users.js";
import type * as util from "../util.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clerk: typeof clerk;
  favorites: typeof favorites;
  http: typeof http;
  newsletters: typeof newsletters;
  portfolios: typeof portfolios;
  submissions: typeof submissions;
  templates: typeof templates;
  uploads: typeof uploads;
  users: typeof users;
  util: typeof util;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
